### ISSUE TITLE
Proposal: Make it easier to call the C-ABI from Rust

### ISSUE THREAD

**Issue by jhugman** [mozilla/uniffi-rs#2331]
The issue I'd like to address here is to make calling the generated C ABI  from **Rust** easier.

## Context

Currently, all uniffi bindings works by:
* lowering from the high level foreign language to a low level representation
* squeezing the low level representation through a C ABI
* then lifting that low level representation into high level Rust types.

![Lifting and lowering in a Swift uniffi binding](https://github.com/user-attachments/assets/11fb887b-340b-45a0-885d-fb14064bbb94)

For languages that can't represent structures directly in C, the bindings need to get to C before calling across into Rust.

For example, the uniffi-bindgen for both gecko-js and React Native, need to generate C++ to call into Rust via the C-ABI.

![Lifting and lowering from Javascript in to C++ then to Rust](https://github.com/user-attachments/assets/4f924d29-6b3c-49ad-8b66-623c6ed16655)

## Intent

The issue I'd like to address here is to make calling this C ABI from **Rust** easier. 

It should be additive to the existing generated Rust.

This will enable writing uniffi adapters for new languages or contexts: e.g. node, via [napi.rs](https://napi.rs); [tauri](https://tauri.app); browser WASM via wasm-bindgen.

It may also open up the way to easier to maintain bindgens for languages with specialized Rust bindings crates (e.g. Ruby, Python, Dart, etc).

To ground this however, my current focus is on WASM, re-using [the Typescript bindings generated by `uniffi-bindgen-react-native`](https://jhugman.github.io/uniffi-bindgen-react-native/idioms/common-types.html). Whether or not we use `wasm-bindgen` is an implementation detail for the purpose of this issue.

![Lifting and lowering from Javascript to Rust, via Rust](https://github.com/user-attachments/assets/8d6270ae-56e4-4250-aea4-2114128d75f7)

I have been thinking of this proposal as "Rust as a foreign language", though this is not quite accurate: it is only the _low-level_ ABI this proposal is targeting.

## Task list

Right now, in order of urgency I think the list of issues that are needed is:

* Ensure that the C-ABI is `pub`, so it can be accessed from Rust as easily as it can be accessed by C.
* Change `gen_ffi_function` to add a low-level async caller function to the C-ABI
	* This is so bindings can use specialised implementations of `Future`.
* Lightweight facade to allow customization of the generation of `extern "C"` code.
	* This would add a trait (in the same way as `log!`) to add annotations and code.

For WASM specifically:

* More options to extract the Component Interface from a crate. Either:
	* Ability to read a WASM bundle in library mode.
	* A serialization/deserialization format generated to a well-known location at build time.

For now, I think I can get started with just the [first](https://github.com/mozilla/uniffi-rs/pull/2329).

With the exception of the last one, I don't think any individual issue is a large amount of work. 

I don't think any of this is on Mozilla's roadmap, so would be happy to do the engineering.

## Next steps?

- [ ] Gather feedback, answer questions
- [ ] Break out task list into separate issues
- [ ] Hack, test, document, land

## Call to action

* Does this conflict with– or align with– existing plans?
* If I do this, would it be landed?
* What would stop this plan working?
* What do you think?

**Comment by bendk** [comment]
IIUC, this could be summarized as allowing a second layer of scaffolding specific to a bindings generator.  Seems like good idea to me, although I can't totally picture how it's going to work out.

One question I had was about linking: IIUC, you would build the normal library with the UniFFI scaffolding, then build a second library with an extra layer of scaffolding, then link to both?  It seems like it would work to me, but it is introducing an extra layer of complexity.  For example, should this extra layer also have checksum/version checks?

My other big-picture question is if any set of bindings would want to share some of this extra scaffolding?  That's kind of what I was trying to do with the `ffi-buffer` feature flag, but I don't think that's the right approach anymore.  I wonder what functions you're planning to add and if they would also be useful for the gecko-js bindings.

> If we could have an intermediate function that did the lifting and lowering, we could use other Futures implementations.

This seems like a no-brainer to me, I can't see any downside to it.  Can an `async fn` also be `extern "C"` though?  Maybe you'd need to drop that part, but I don't think that affects your plans.

> It may also open up the way to easier to maintain bindgens for languages with specialized Rust bindings crates (e.g. Ruby, Python, Dart, etc).

Would this mean something like generating Rust code that uses the `pyo3` crate to generate the Python bindings?  That could be pretty nice.

**Comment by jhugman** [comment]
> question I had was about linking: IIUC, you would build the normal library with the UniFFI scaffolding, then build a second library with an extra layer of scaffolding, then link to both? It seems like it would work to me, but it is introducing an extra layer of complexity.

I was hoping that this could be made easier by the binding generator pass in a trait which changed the behaviour of the scaffolding generation. i.e. the second layer of  generated at the same time as the first, but I hadn't worked out the mechanics of how this works.


>  if any set of bindings would want to share some of this extra scaffolding?

Yes!

I'd hope that the second layer of scaffolding would be relatively straightforward, but paramterizable: though at the moment, I think I'll be able to use type aliasing to most of the work, and switch out a tiny runtime between `wasm-bindgen` and `napi-rs`. The runtime provides the type-aliases and a finite number of inlineable converters.

I'm expecting it to get a bit harder once I start adding callback interfaces.

**Comment by jhugman** [comment]
>>  If we could have an intermediate function that did the lifting and lowering, we could use other Futures implementations.

> This seems like a no-brainer to me, I can't see any downside to it. Can an async fn also be extern "C" though? Maybe you'd need to drop that part, but I don't think that affects your plans.

Brilliant!

Ah yes, I think you're right about the `extern "C"`.

This should be a straightforward change but for one thing: `*const c_void` can't be send across the thread boundary. _I_ would change the low level representation of an `Arc` to something else—e.g. a `u64`—but I thought you'd have a better plan than that. 

Other than that I think it's a single file change.
