### ISSUE TITLE
[META] Miscellaneous Push technical debt & code cleanup

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/uniffi-rs#770]
Filing this meta to consider the various minor changes to the surface area of the push component that I believe can be tackled in smaller issues (most of these are great for contributors!). **File separate issues for these if you're working on it**:

* [ ] API Documentation: Rust and KDocs - formatting, add missing, correct, etc.
  * [ ] #2069 - Document KeyInfo values are base64 encoded
  * The only issues I don't think a new contributor should work on since it requires context of the internal component.
* [ ] Code clean-up in Rust:
  * [ ] More unit tests in the Rust layer.
  * [ ] Move Rust PushManager impl [to a trait](https://github.com/mozilla/application-services/blob/master/components/push/src/subscriber.rs#L38) only if it assisted with testing.
* [ ] Code clean-up in Kotlin:
  * [ ] Move `init` block code to an initializer method (debatable).
  * [ ] Use `data class` for POJOs: `KeyInfo`, `SubscriptionInfo`, `SubscriptionResponse`, etc.
  * [ ] Use types for `httpProtocol` (in Rust too?): `http`, `https`.
  * [ ] Use types for `encoding` (in Rust too?): `aesgcm`, `aes128gcm`.
  * [ ] Add error handling for `InternalPanic` in Kotlin `init` block.
  * [ ] `decrypt` should return the scope as well.
    * [ ] Deprecate `dispatchInfoForChid` after that.
  * [ ] #2704 - Accept appServerKey as a ByteArray
  * [ ] #2705 - Throw exceptions on invalid push subscriptions created

**Comment by data-sync-user** [comment]
➤ Thom Chiovoloni commented:

> Move Rust PushManager impl to a trait

After some discussion in slack: We would take this if it helped add further testing (if other code is moved to use the trait, which tests mock out), but wouldn't take a patch that just does this on it's own, as it increases the maintenance burden of the rust PushManager.
